# Generated by Django 6.1.2 on 2026-10-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ডেভেলপার', max_length=100, verbose_name='নাম')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='developer/', verbose_name='ছবি')),
                ('address', models.TextField(blank=True, default='', verbose_name='ঠিকানা')),
                ('facebook', models.URLField(blank=True, default='', verbose_name='Facebook লিংক')),
                ('whatsapp', models.CharField(blank=True, default='', max_length=20, verbose_name='WhatsApp নম্বর')),
                ('is_visible', models.BooleanField(default=True, verbose_name='দেখাবে')),
            ],
            options={
                'verbose_name': 'ডেভেলপার কার্ড',
                'verbose_name_plural': 'ডেভেলপার কার্ড',
            },
        ),
        migrations.CreateModel(
            name='EventSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='আইডি কার্ড সিস্টেম', max_length=200, verbose_name='ইভেন্ট / প্রতিষ্ঠানের নাম')),
                ('institution_address', models.TextField(blank=True, default='', verbose_name='প্রতিষ্ঠানের ঠিকানা')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='লোগো')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='ব্যাকগ্রাউন্ড ছবি')),
                ('background_color', models.CharField(default='#1e3a5f', max_length=20, verbose_name='ব্যাকগ্রাউন্ড কালার')),
                ('gradient_start', models.CharField(default='#667eea', max_length=20, verbose_name='গ্রেডিয়েন্ট শুরু')),
                ('gradient_end', models.CharField(default='#764ba2', max_length=20, verbose_name='গ্রেডিয়েন্ট শেষ')),
                ('card_primary_color', models.CharField(default='#4f46e5', max_length=20, verbose_name='কার্ড প্রাইমারি কালার')),
                ('card_secondary_color', models.CharField(default='#7c3aed', max_length=20, verbose_name='কার্ড সেকেন্ডারি কালার')),
                ('text_color', models.CharField(default='#ffffff', max_length=20, verbose_name='টেক্সট কালার')),
                ('show_name', models.BooleanField(default=True, verbose_name='নাম দেখাবে')),
                ('show_class', models.BooleanField(default=True, verbose_name='ক্লাস দেখাবে')),
                ('show_roll', models.BooleanField(default=True, verbose_name='রোল দেখাবে')),
                ('show_designation', models.BooleanField(default=True, verbose_name='পদবি দেখাবে')),
                ('show_blood_group', models.BooleanField(default=True, verbose_name='ব্লাড গ্রুপ দেখাবে')),
                ('show_address', models.BooleanField(default=True, verbose_name='ঠিকানা দেখাবে')),
                ('show_phone', models.BooleanField(default=True, verbose_name='ফোন দেখাবে')),
                ('show_email', models.BooleanField(default=True, verbose_name='ইমেইল দেখাবে')),
                ('show_profile_pic', models.BooleanField(default=True, verbose_name='প্রোফাইল পিক দেখাবে')),
                ('show_qr', models.BooleanField(default=True, verbose_name='QR কোড দেখাবে')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ইভেন্ট সেটিংস',
                'verbose_name_plural': 'ইভেন্ট সেটিংস',
            },
        ),
    ]
