# Generated by Django 6.1.2 on 2026-10-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='শিরোনাম')),
                ('content', models.TextField(blank=True, verbose_name='বিস্তারিত')),
                ('image', models.ImageField(blank=True, null=True, upload_to='notices/', verbose_name='ছবি')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='notice_pdfs/', verbose_name='PDF ফাইল')),
                ('is_published', models.BooleanField(default=True, verbose_name='প্রকাশিত')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'নোটিশ',
                'verbose_name_plural': 'নোটিশসমূহ',
                'ordering': ['-created_at'],
            },
        ),
    ]
