# Generated by Django 6.1.2 on 2026-10-07 13:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=150, verbose_name='নাম')),
                ('class_name', models.CharField(blank=True, max_length=50, verbose_name='ক্লাস')),
                ('roll', models.CharField(blank=True, max_length=30, verbose_name='রোল')),
                ('designation', models.CharField(blank=True, max_length=100, verbose_name='পদবি')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, verbose_name='ব্লাড গ্রুপ')),
                ('address', models.TextField(blank=True, verbose_name='ঠিকানা')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='ফোন')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ইমেইল')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='প্রোফাইল পিকচার')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
            ],
            options={
                'verbose_name': 'স্টুডেন্ট / মেম্বার',
                'verbose_name_plural': 'স্টুডেন্ট / মেম্বারগণ',
                'ordering': ['-created_at'],
            },
        ),
    ]
